/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectmanagement;

import javax.swing.DefaultListModel;

/**
 *
 * @author Islam
 */
public class Projects extends javax.swing.JInternalFrame {

    /**
     * Creates new form Projects
     */
    public Projects() {
        initComponents();
        this.setBounds(5,5,750,530);
        LoginForm LF = new LoginForm();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
        DefaultListModel proj = new DefaultListModel();
        for (int i = 0; i < LF.c.getAllProjects().size(); i++){
            proj.addElement(LF.c.getAllProjects().get(i).getID()+"");
        }
        jList1.setModel(proj);
    }
    
    public void writeProject(int id){
        LoginForm LF = new LoginForm();
        nameLabel.setText("Name:");
        deadlineLabel.setText("Deadline:");
        completeLabel.setText("Complete:");
        tasksLabel.setText("Tasks:");
        Name.setText(LF.c.getProjectById(id).getName());
        Deadline.setText(LF.c.getProjectById(id).getProjectDeadLine().toString());
        Complete.setText(LF.c.getProjectById(id).getProgress() + "");
        Tasks.setText(LF.c.getProjectById(id).getTasks().size() + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        nameLabel = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        completeLabel = new javax.swing.JLabel();
        Complete = new javax.swing.JLabel();
        Deadline = new javax.swing.JLabel();
        deadlineLabel = new javax.swing.JLabel();
        Tasks = new javax.swing.JLabel();
        tasksLabel = new javax.swing.JLabel();

        jList1.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        nameLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N

        Name.setFont(new java.awt.Font("Segoe UI Light", 0, 25)); // NOI18N

        completeLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N

        Complete.setFont(new java.awt.Font("Segoe UI Light", 0, 25)); // NOI18N

        Deadline.setFont(new java.awt.Font("Segoe UI Light", 0, 25)); // NOI18N

        deadlineLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N

        Tasks.setFont(new java.awt.Font("Segoe UI Light", 0, 25)); // NOI18N

        tasksLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel)
                    .addComponent(completeLabel)
                    .addComponent(deadlineLabel)
                    .addComponent(tasksLabel)
                    .addComponent(Name)
                    .addComponent(Complete)
                    .addComponent(Deadline)
                    .addComponent(Tasks))
                .addContainerGap(533, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Name)
                .addGap(34, 34, 34)
                .addComponent(completeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Complete)
                .addGap(34, 34, 34)
                .addComponent(deadlineLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Deadline)
                .addGap(34, 34, 34)
                .addComponent(tasksLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tasks)
                .addContainerGap(366, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        LoginForm LF = new LoginForm();
        int selected = Integer.parseInt(jList1.getSelectedValue());
        writeProject(selected);
    }//GEN-LAST:event_jList1ValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Complete;
    private javax.swing.JLabel Deadline;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Tasks;
    private javax.swing.JLabel completeLabel;
    private javax.swing.JLabel deadlineLabel;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel tasksLabel;
    // End of variables declaration//GEN-END:variables
}
