/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectmanagement;

import javax.swing.DefaultListModel;

/**
 *
 * @author Islam
 */
public class Reports extends javax.swing.JPanel {

    /**
     * Creates new form Reports
     */
    public Reports() {
        initComponents();
        this.setBounds(5,5,750,530);
        LoginForm LF = new LoginForm();
        if(LF.c.currentUserRole != 3){
            jPanel2.setVisible(false);
        }
        updateList();
    }
    
    public void writeReport(int id){
        LoginForm LF = new LoginForm();
        ReportLabel.setText("Report:");
        ToLabel.setText("To:");
        AboutLabel.setText("About:");
        Report.setText(LF.c.getReportById(id).getReport());
        TL.setText(LF.c.getTeamLeaderById(LF.c.getReportById(id).getTeamLeaderId()).getFirstName() + " " + LF.c.getTeamLeaderById(LF.c.getReportById(id).getTeamLeaderId()).getLastName());
        Employee.setText(LF.c.getEmployeeById(LF.c.getReportById(id).getEmpId()).getFirstName() + " " + LF.c.getEmployeeById(LF.c.getReportById(id).getEmpId()).getLastName());
    }
    
    public void updateList(){
        LoginForm LF = new LoginForm();
        DefaultListModel ReportsModel = new DefaultListModel();
            for (int i = 0; i < LF.c.getAllReport().size(); i++){
                ReportsModel.addElement(LF.c.getAllReport().get(i).getId()+"");
            }
        Reports.setModel(ReportsModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        Reports = new javax.swing.JList<>();
        ReportLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Report = new javax.swing.JLabel();
        ToLabel = new javax.swing.JLabel();
        TL = new javax.swing.JLabel();
        AboutLabel = new javax.swing.JLabel();
        Employee = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        About = new javax.swing.JTextField();
        To = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ReportText = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Reports.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        Reports.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ReportsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(Reports);

        ReportLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel2.setText("Reports:");

        Report.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N

        ToLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N

        TL.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N

        AboutLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N

        Employee.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(220, 220, 220));

        jButton1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jButton1.setText("Send Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        About.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N

        To.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N

        ReportText.setColumns(14);
        ReportText.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        ReportText.setRows(3);
        jScrollPane2.setViewportView(ReportText);

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel8.setText("Report:");

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel9.setText("To:");

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel10.setText("About:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addComponent(To)
                            .addComponent(About))))
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(To, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(About, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ReportLabel)
                                .addGap(96, 96, 96)
                                .addComponent(Report, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ToLabel)
                                        .addGap(147, 147, 147)
                                        .addComponent(TL))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(AboutLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Employee)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(109, 109, 109))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ReportLabel)
                            .addComponent(Report))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ToLabel)
                            .addComponent(TL))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AboutLabel)
                            .addComponent(Employee))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LoginForm LF = new LoginForm();
        String report = ReportText.getText();
        int tlId = Integer.parseInt(To.getText());
        int empId = Integer.parseInt(About.getText());
        try{
            LF.c.makeReport("TEST", empId, tlId);
        }
        catch(Exception e){

        }
        updateList();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ReportsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ReportsValueChanged
        int selected = Integer.parseInt(Reports.getSelectedValue());
        writeReport(selected);
    }//GEN-LAST:event_ReportsValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField About;
    private javax.swing.JLabel AboutLabel;
    private javax.swing.JLabel Employee;
    private javax.swing.JLabel Report;
    private javax.swing.JLabel ReportLabel;
    private javax.swing.JTextArea ReportText;
    private javax.swing.JList<String> Reports;
    private javax.swing.JLabel TL;
    private javax.swing.JTextField To;
    private javax.swing.JLabel ToLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
