/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectmanagement;

import javax.swing.DefaultListModel;

/**
 *
 * @author Islam
 */
public class Tasks extends javax.swing.JInternalFrame {

    /**
     * Creates new form Tasks
     */
    public Tasks() {
        initComponents();
        this.setBounds(5,5,750,530);
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
        updateLists();
    }
    
    public void updateLists(){
        LoginForm LF = new LoginForm();
        if(LF.c.currentUserRole == 1){
            DefaultListModel fTasks = new DefaultListModel();
            for (int i = 0; i < LF.c.empSession.getFinishedTasks().size(); i++){
                fTasks.addElement(LF.c.empSession.getFinishedTasks().get(i).getId()+"");
            }
            Finished.setModel(fTasks);
            DefaultListModel pTasks = new DefaultListModel();
            for (int i = 0; i < LF.c.empSession.getPendingTasks().size(); i++){
                pTasks.addElement(LF.c.empSession.getPendingTasks().get(i).getId()+"");
            }
            Pending.setModel(pTasks);
        }
        else{
            DefaultListModel fTasks = new DefaultListModel();
            for (int i = 0; i < LF.c.getAllFinishedTasks().size(); i++){
                fTasks.addElement(LF.c.getAllFinishedTasks().get(i).getId()+"");
            }
            Finished.setModel(fTasks);
            jTabbedPane1.remove(0);
        }
    }
    public void writeTask(int id){
        LoginForm LF = new LoginForm();
        task t = LF.c.getTaskById(id);
        Name.setText(t.getTaskName());
        Disc.setText(t.getTaskDesc());
        Project.setText(LF.c.getProjectById(LF.c.getTaskById(id).getProjectId()).getName());
        DefaultListModel tTeam = new DefaultListModel();
        try{
                for (int i = 0; i < t.getAllCoders().size(); i++){
                tTeam.addElement(t.getAllCoders().get(i).getFirstName() + " " + t.getAllCoders().get(i).getLastName());
            }
        }
        catch(Exception e){
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Pending = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Finished = new javax.swing.JList<>();
        Name = new javax.swing.JLabel();
        Disc = new javax.swing.JLabel();
        Project = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Team = new javax.swing.JList<>();

        Pending.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        Pending.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PendingMouseClicked(evt);
            }
        });
        Pending.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                PendingValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(Pending);

        jButton1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jButton1.setText("Finish");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Pending", jPanel1);

        Finished.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FinishedMouseClicked(evt);
            }
        });
        Finished.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                FinishedValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(Finished);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Finished", jPanel2);

        Name.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        Name.setText("Task Name");

        Disc.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        Disc.setText("Discription");
        Disc.setToolTipText("");
        Disc.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        Project.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        Project.setText("Project");

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel4.setText("Team:");

        Team.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jScrollPane4.setViewportView(Team);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Project, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                    .addComponent(Disc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Project, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Disc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LoginForm LF = new LoginForm();
        int taskId = Integer.parseInt(Pending.getSelectedValue());
        LF.c.empSession.finishTask(taskId);
        updateLists();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PendingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PendingMouseClicked
        
    }//GEN-LAST:event_PendingMouseClicked

    private void FinishedValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_FinishedValueChanged
        int selected = Integer.parseInt(Finished.getSelectedValue());
        writeTask(selected);
    }//GEN-LAST:event_FinishedValueChanged

    private void FinishedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FinishedMouseClicked

    }//GEN-LAST:event_FinishedMouseClicked

    private void PendingValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_PendingValueChanged
        int selected = Integer.parseInt(Pending.getSelectedValue());
        System.out.println(selected);
        writeTask(selected);
    }//GEN-LAST:event_PendingValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Disc;
    private javax.swing.JList<String> Finished;
    private javax.swing.JLabel Name;
    private javax.swing.JList<String> Pending;
    private javax.swing.JLabel Project;
    private javax.swing.JList<String> Team;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
